[build]
builder = "nixpacks"

[deploy]
startCommand = "composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=8080"

[env]
PORT = "8080"
